- hosts: claudinha
  sudo: True
  gather_facts: yes
  vars_files:
    - vars/claudinha.yml
  environment:
    LC_ALL: en_GB.UTF-8

  pre_tasks:
  - name: Create project directory
    file:
      path: /opt/claudinha/{{ item.dest }}
      state: directory
      owner: pi
      group: claudinha
      mode: 0775
    with_items:
      - { dest: 'frontend' }
      - { dest: 'backend' }
      - { dest: 'venv' }

  - name: Synchronize directory
    synchronize:
      src: ./{{ item.dest }}/
      dest: /opt/claudinha/{{ item.dest }}
      group: no
      owner: no
      delete: yes
      recursive: yes
      archive: no
      rsync_opts:
        - "--exclude=tests"
        - "--exclude=.cache"
        - "--exclude=.pyc"
        - "--exclude=__pycache__"
    with_items:
      - { dest: 'frontend' }
      - { dest: 'backend' }

  roles:
  - common
  - gunicorn
  - supervisor
  - application

  post_tasks:
  - name: Test claudinha app
    wait_for: host={{ inventory_hostname }} port=80
